import type { Language } from './types';

export const CATEGORIES: string[] = [
    'All', 'Electronics', 'Smart Home', 'Wearables', 'Gaming', 'Accessories'
];

export const PRICE_RANGES = [
    { key: 'all', labelKey: 'all_prices' },
    { key: '0-50', label: '$0 - $50' },
    { key: '50-200', label: '$50 - $200' },
    { key: '200+', label: '$200+' }
];

export const RATING_FILTERS = [
    { key: 0, labelKey: 'all_ratings' },
    { key: 4, labelKey: 'four_stars_up' },
    { key: 3, labelKey: 'three_stars_up' }
];

export const LOCAL_STORAGE_KEYS = {
    SELLERS: 'innovativegadget_sellers',
    BUYERS: 'innovativegadget_buyers',
    PRODUCTS: 'sellerProducts',
    ORDERS: 'innovativegadget_orders',
    THEME: 'theme',
    BROWSING_HISTORY: 'innovativegadget_browsing_history',
};

export const SESSION_STORAGE_KEYS = {
    SELLER_ID: 'currentSellerId',
    BUYER_ID: 'currentBuyerId',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
    en: {
        'search_placeholder': 'Search for gadgets...',
        'categories': 'Categories',
        'all': 'All',
        'electronics': 'Electronics',
        'clothing': 'Smart Home', // Re-purposing
        'groceries': 'Wearables', // Re-purposing
        'mobile_phones': 'Gaming', // Re-purposing
        'beauty_health': 'Accessories', // Re-purposing
        'add_to_cart': 'Add to Cart',
        'reviews': 'reviews',
        'vendor_ai_assistant': 'Vendor AI Assistant',
        'ai_description': 'Generate a compelling product description with AI!',
        'product_keywords': 'Enter product keywords (e.g., "wireless noise-cancelling headphones")',
        'generate_description': 'Generate',
        'generating': 'Generating...',
        'shopping_cart': 'Shopping Cart',
        'shopping': 'Shopping',
        'wishlist': 'Wishlist',
        'my_wishlist': 'My Wishlist',
        'empty_wishlist': 'Your wishlist is empty.',
        'empty_wishlist_prompt': 'Browse products and add your favorites by clicking the heart icon.',
        'home': 'Home',
        'empty_cart': 'Your cart is empty.',
        'subtotal': 'Subtotal',
        'proceed_to_checkout': 'Proceed to Checkout',
        'checkout': 'Checkout',
        'delivery_details': 'Delivery Details',
        'full_name': 'Full Name',
        'phone_number': 'Phone Number',
        'delivery_address': 'Delivery Address',
        'payment_method': 'Payment Method',
        'cash_on_delivery': 'Credit Card',
        'orange_money': 'PayPal',
        'africell_money': 'Google Pay',
        'syllogy_mobile_money': 'Apple Pay',
        'natcom_top_up': 'Crypto',
        'place_order': 'Place Order',
        'order_placed_success_title': 'Order Placed Successfully!',
        'order_placed_success_desc': "Thank you for your purchase. You can track the status of your order below.",
        'your_order_id': 'Your Order ID is:',
        'continue_shopping': 'Continue Shopping',
        'close': 'Close',
        'english': 'English',
        'krio': 'Krio',
        'sort_by': 'Sort by',
        'sort_default': 'Default',
        'sort_price_asc': 'Price: Low to High',
        'sort_price_desc': 'Price: High to Low',
        'seller_dashboard': 'Seller Dashboard',
        'add_new_product': 'Add New Product',
        'product_name': 'Product Name',
        'product_description': 'Product Description',
        'product_price': 'Price ($)',
        'product_original_price': 'Original Price ($) (for sales)',
        'product_stock': 'Stock Count (for product without variants)',
        'product_category': 'Category',
        'product_image': 'Product Image(s)',
        'upload_image': 'Upload Image(s)',
        'image_preview': 'Image Previews',
        'add_product': 'Add Product',
        'my_products': 'My Products',
        'my_profile': 'My Profile',
        'order_history': 'Order History',
        'no_products_added': 'You have not added any products yet.',
        'no_orders_yet': 'You have no orders yet.',
        'order_id': 'Order ID',
        'date': 'Date',
        'total': 'Total',
        'status': 'Status',
        'buyer_information': 'Buyer Information',
        'items_in_order': 'Items in this Order',
        'fill_all_fields': 'Please fill out all fields and upload at least one image.',
        'max_images_error': 'You can upload a maximum of 5 images.',
        'seller_login_signup': 'Seller Login / Sign Up',
        'logout': 'Logout',
        'login': 'Login',
        'signup': 'Sign Up',
        'email': 'Email Address',
        'store_name': 'Store Name',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'login_prompt': 'Already have an account?',
        'signup_prompt': 'Don\'t have an account?',
        'login_error': 'Invalid email or password.',
        'signup_email_exists': 'An account with this email already exists.',
        'signup_password_mismatch': 'Passwords do not match.',
        'signup_invalid_email': 'Please enter a valid email address.',
        'signup_password_weak': 'Password must be at least 8 characters long, contain at least one number, and one special character (!@#$%).',
        'auth_storage_error': 'Could not access local storage. Please ensure it is enabled in your browser.',
        'update_profile': 'Update Profile',
        'profile_updated_success': 'Your profile has been updated successfully!',
        'profile_update_error': 'Failed to update profile. Please try again.',
        'email_in_use_error': 'This email is already in use by another account.',
        'forgot_password': 'Forgot Password?',
        'reset_password': 'Reset Password',
        'reset_password_prompt': "Enter your email and we'll send you a link to reset your password.",
        'send_reset_link': 'Send Reset Link',
        'back_to_login': 'Back to Login',
        'reset_link_sent': 'If an account with that email exists, a password reset link has been sent.',
        'store_name_required': 'Store name is required.',
        'customer_service': 'Customer Service',
        'help_center': 'Help Center',
        'how_to_buy': 'How to Buy',
        'track_your_order': 'Track Your Order',
        'track_order': 'Track Order',
        'track_order_placeholder': 'Enter your Order ID (e.g., IG-123...)',
        'track_order_button': 'Track',
        'invalid_order_id_format': 'Please enter a valid Order ID (e.g., IG-123456789).',
        'order_not_found_error': 'Order not found. Please check the ID and try again.',
        'returns_refunds': 'Returns & Refunds',
        'about_salonekart': 'About Innovative Gadget',
        'about_us': 'About Us',
        'careers': 'Careers',
        'terms_conditions': 'Terms & Conditions',
        'privacy_policy': 'Privacy Policy',
        'sell_on_salonekart': 'Sell on Innovative Gadget',
        'start_selling': 'Start Selling',
        'vendor_hub': 'Vendor Hub',
        'success_stories': 'Success Stories',
        'connect_with_us': 'Connect with Us',
        'chatbot_greeting': "Hi! I'm your Innovative Gadget assistant. How can I help you today?",
        'chatbot_error': "Sorry, I'm having a little trouble connecting right now. Please try again later.",
        'chatbot_placeholder': 'Ask about products, shipping...',
        'chatbot_typing': 'Assistant is typing...',
        'chatbot_title': 'Gadget Assistant',
        'buyer': 'Buyer',
        'seller': 'Seller',
        'login_signup': 'Login / Sign Up',
        'my_account': 'My Account',
        'buyer_dashboard': 'Buyer Dashboard',
        'dashboard': 'Dashboard',
        'analytics': 'Analytics',
        'top_selling_products': 'Top Selling Products',
        'units_sold': 'Units Sold',
        'stock': 'Stock',
        'update': 'Update',
        'stock_updated': 'Updated!',
        'edit_product_details': 'Edit Product Details',
        'compare': 'Compare',
        'remove_from_compare': 'Remove from Compare',
        'compare_items': 'Compare Items',
        'clear_all': 'Clear All',
        'comparison_limit_error': 'You can compare a maximum of 4 products.',
        'product_comparison': 'Product Comparison',
        'remove': 'Remove',
        'price': 'Price',
        'rating': 'Rating',
        'stock_status': 'Stock Status',
        'in_stock': 'In Stock',
        'low_stock': 'Low Stock',
        'out_of_stock': 'Out of Stock',
        'price_range': 'Price Range',
        'all_prices': 'All Prices',
        'all_ratings': 'All Ratings',
        'four_stars_up': '4 Stars & Up',
        'three_stars_up': '3 Stars & Up',
        'visual_search_title': 'Search by Image',
        'upload_image_prompt': 'Upload a photo to find similar gadgets.',
        'finding_similar_products': 'Scanning for similar items...',
        'no_similar_products': 'No similar products found. Try a different image.',
        'virtual_try_on': 'AR Preview',
        'try_on_prompt': 'Use your camera to see this gadget in your room.',
        'generating_preview': 'Generating your preview...',
        'subscribe_and_save': 'Subscribe & Save',
        'subscribe_prompt': 'Save 10% with monthly delivery.',
        'one_time_purchase': 'One-time purchase',
        'subscription': 'Subscription',
        'my_rewards': 'My Rewards',
        'loyalty_program_title': 'Loyalty Program',
        'points_balance': 'Your Points Balance',
        'your_tier': 'Your Tier',
        'bronze': 'Bronze',
        'silver': 'Silver',
        'gold': 'Gold',
        'how_to_earn': 'How to Earn Points',
        'earn_points_desc': 'Earn 1 point for every $1 you spend!',
        'upload_review_image': 'Upload Photo',
        'review_summary': 'Review Summary by AI',
        'summarizing_reviews': 'Summarizing reviews...',
        'shop_the_look': 'Shop the Look',
        'contact_support': 'Contact Support',
        'your_message': 'Your Message',
        'submit_ticket': 'Submit Ticket',
        'ticket_submitted_success': 'Your support ticket has been submitted!',
        'ai_search_suggestions': 'Suggestions',
        'did_you_mean': 'Did you mean:',
        // New keys for 5 unique features
        'make_an_offer': 'Make an Offer',
        'price_negotiation': 'Price Negotiation',
        'negotiation_greeting': "Let's make a deal! What's your best offer?",
        'negotiation_placeholder': 'Enter your offer price...',
        'offer_accepted': 'Offer Accepted!',
        'voice_search_prompt': 'Speak to search for products...\n(e.g., "Show me wireless earbuds")',
        'for_you': 'For You',
        'all_products': 'All Products',
        'personalized_recommendations': 'Personalized Recommendations',
        'vendor_spotlight': 'Vendor Spotlight',
        'my_story': 'My Story',
        'tell_us_your_story': 'Tell Us Your Story',
        'story_prompt': 'Enter a few bullet points about your business, your craft, or what makes your products special. Our AI will turn it into a beautiful story for our homepage!',
        'generate_story': 'Generate My Story',
        'loyalty_and_quests': 'My Rewards', // Updated from "Loyalty & Quests"
        'your_quests': 'Your Quests',
        'completed': 'Completed',
        'get_new_quests': 'Get New Quests',
        // Order Confirmation
        'confirm_receipt': 'Confirm Receipt',
        'mark_as_shipped': 'Mark as Shipped',
        'mark_as_delivered': 'Mark as Delivered',
        'status_pending': 'Pending',
        'status_shipped': 'Shipped',
        'status_delivered': 'Delivered',
        'status_completed': 'Completed',
        'payment_method_description_cod': 'Pay securely with your credit or debit card.',
        'payment_method_description_mobile': 'Pay securely with your digital wallet.',
        'mobile_money_number_label': 'Account Email / Phone Number',
        'mobile_money_number_placeholder': 'e.g., user@example.com',
        'cod_instruction': 'Your payment is processed securely.',
        'secure_transaction_info': 'Your transaction is secured with end-to-end encryption.',
    },
    krio: {
        'search_placeholder': 'Luk fo gadjet dɛn...',
        'categories': 'Kayn Tin Dɛn',
        'all': 'Ɔl',
        'electronics': 'Ɛlɛktrɔnik Tin Dɛn',
        'clothing': 'Smat Hom',
        'groceries': 'Wierabul Dɛn',
        'mobile_phones': 'Gem Dɛn',
        'beauty_health': 'Asɛsɛri Dɛn',
        'add_to_cart': 'Put Insay Kat',
        'reviews': ' रिव्यूस',
        'vendor_ai_assistant': 'Vɛnda AI Asist',
        'ai_description': 'Mek AI rayt fayn diskripshɔn fɔ yu prodɔkt!',
        'product_keywords': 'Put di prodɔkt in kiwɔd (ɛg "wayales nɔys-kansɛlin ɛdfon")',
        'generate_description': 'Mek Am',
        'generating': 'I de mek am...',
        'shopping_cart': 'Shɔpin Kat',
        'shopping': 'Shɔpin',
        'wishlist': 'Wishlist',
        'my_wishlist': 'Mi Wishlist',
        'empty_wishlist': 'Yu wishlist ɛmti.',
        'empty_wishlist_prompt': 'Luk fɔ prodɔkt dɛn ɛn put di wan dɛn we yu lɛk bay klik di at aykɔn.',
        'home': 'Hom',
        'empty_cart': 'Yu kat ɛmti.',
        'subtotal': 'Subtotal',
        'proceed_to_checkout': 'Go fɔ Pe',
        'checkout': 'Pement',
        'delivery_details': 'Usay fɔ Kɛr Am Go',
        'full_name': 'Yu Ful Nem',
        'phone_number': 'Fon Nɔmba',
        'delivery_address': 'Adres fɔ Diliva',
        'payment_method': 'Aw fɔ Pe',
        'cash_on_delivery': 'Krɛdit Kad',
        'orange_money': 'PayPal',
        'africell_money': 'Google Pay',
        'syllogy_mobile_money': 'Apple Pay',
        'natcom_top_up': 'Kripto',
        'place_order': 'Mek di Ɔda',
        'close': 'Klɔs',
        'english': 'Inglish',
        'krio': 'Krio',
        'sort_by': 'Sɔt bay',
        'sort_default': 'Normal',
        'sort_price_asc': 'Prayz: Smol to Big',
        'sort_price_desc': 'Prayz: Big to Smol',
        'seller_dashboard': 'Sɛla Dashbɔd',
        'add_new_product': 'Put Nyu Prodɔkt',
        'product_name': 'Prodɔkt Nem',
        'product_description': 'Diskripshɔn fɔ di Prodɔkt',
        'product_price': 'Prayz ($)',
        'product_original_price': 'Fɔs Prayz ($) (fɔ sel)',
        'product_stock': 'Stɔk (fɔ prodɔkt we nɔ gɛt variant)',
        'product_category': 'Kayn Tin',
        'product_image': 'Prodɔkt Pikchɔ(dɛn)',
        'upload_image': 'Put Pikchɔ(dɛn)',
        'image_preview': 'Pikchɔ Privyu Dɛn',
        'add_product': 'Put di Prodɔkt',
        'my_products': 'Mi Prodɔkt Dɛn',
        'my_profile': 'Mi Profayl',
        'order_history': 'Ɔda Istri',
        'no_products_added': 'Yu nɔ put ɛni prodɔkt yet.',
        'no_orders_yet': 'Yu nɔ gɛt ɔda yet.',
        'order_id': 'Ɔda ID',
        'date': 'Det',
        'total': 'Total',
        'status': 'Status',
        'buyer_information': 'Infɔmeshɔn fɔ di Pɔsin we Bay',
        'items_in_order': 'Tin dɛn insay dis Ɔda',
        'fill_all_fields': 'Plis, rayt ɔl di tin dɛn na di bɔks dɛn ɛn put at list wan pikchɔ.',
        'max_images_error': 'Yu go ebul fɔ ɔplod nɔmɔ 5 pikchɔ.',
        'seller_login_signup': 'Sɛla Lɔgin / Sain Ɔp',
        'logout': 'Lɔg Aut',
        'login': 'Lɔgin',
        'signup': 'Sain Ɔp',
        'email': 'Imel Adrɛs',
        'store_name': 'Sto Nem',
        'password': 'Paswɔd',
        'confirm_password': 'Rayt di Paswɔd Bak',
        'login_prompt': 'Yu gɛt akant ɔlrɛdi?',
        'signup_prompt': 'Yu nɔ gɛt akant?',
        'login_error': 'Di imel ɔ paswɔd nɔ kɔrɛkt.',
        'signup_email_exists': 'Sɔmbɔdi de yuz dis imel ɔlrɛdi.',
        'signup_password_mismatch': 'Di paswɔd dɛn nɔ mach.',
        'signup_invalid_email': 'Plis, rayt kɔrɛkt imel adrɛs.',
        'signup_password_weak': 'Di paswɔd fɔ pas 8 karakta, ɛn i fɔ gɛt nɔmba ɛn spɛshal mak insay (!@#$%).',
        'auth_storage_error': 'Wi nɔ ebul fɔ akses lokal stɔrej. Plis, mek shɔ se i de wok na yu brawza.',
        'update_profile': 'Apdet Profayl',
        'profile_updated_success': 'Yu profayl dɔn apdet!',
        'profile_update_error': 'Wi nɔ ebul fɔ apdet yu profayl. Plis, tray bak.',
        'email_in_use_error': 'Sɔmbɔdi ɔlrɛdi de yuz dis imel.',
        'forgot_password': 'Yu Fɔgɛt di Paswɔd?',
        'reset_password': 'Chenj Paswɔd',
        'reset_password_prompt': 'Rayt yu imel ɛn wi go sɛn yu link fɔ chenj yu paswɔd.',
        'send_reset_link': 'Sɛn di Link',
        'back_to_login': 'Go Bak fɔ Lɔgin',
        'reset_link_sent': 'If akant de wit da imel de, wi dɔn sɛn link fɔ chenj di paswɔd.',
        'store_name_required': 'Sto nem nid fɔ de.',
        'customer_service': 'Kɔstɔma Sevis',
        'help_center': 'Hɛp Sɛnta',
        'how_to_buy': 'Aw fɔ Bay',
        'track_your_order': 'Trak Yu Ɔda',
        'track_order': 'Trak Ɔda',
        'track_order_placeholder': 'Put yu Ɔda ID (ɛg, IG-123...)',
        'track_order_button': 'Trak',
        'invalid_order_id_format': 'Plis, rayt kɔrɛkt Ɔda ID (ɛg, IG-123456789).',
        'order_not_found_error': 'Wi nɔ si di ɔda. Plis, chɛk di ID ɛn tray bak.',
        'returns_refunds': 'Ritɔn & Rifɔnd',
        'about_salonekart': 'Bɔt Innovative Gadget',
        'about_us': 'Bɔt Wi',
        'careers': 'Wak',
        'terms_conditions': 'Tɛm & Kɔndishɔn',
        'privacy_policy': 'Prayvesi Pɔlisi',
        'sell_on_salonekart': 'Sɛl na Innovative Gadget',
        'start_selling': 'Stat fɔ Sɛl',
        'vendor_hub': 'Vɛnda Hɔb',
        'success_stories': 'Sɔksɛs Stori Dɛn',
        'connect_with_us': 'Kɔnɛkt Wit Wi',
        'chatbot_greeting': "Kushe! Na mi yu Innovative Gadget asistant. Aw a go ɛp yu tide?",
        'chatbot_error': "Sɔri, a nɔ de ebul fɔ kɔnɛkt naw naw. Plis tray bak smɔl tɛm.",
        'chatbot_placeholder': 'Aks bɔt prodɔkt, shipin...',
        'chatbot_typing': 'Asistant de rayt...',
        'chatbot_title': 'Gadjet Asistant',
        'buyer': 'Baya',
        'seller': 'Sɛla',
        'login_signup': 'Lɔgin / Sain Ɔp',
        'my_account': 'Mi Akant',
        'buyer_dashboard': 'Baya Dashbɔd',
        'dashboard': 'Dashbɔd',
        'analytics': 'Analitiks',
        'top_selling_products': 'Prodɔkt dɛn we de Sɛl Pas ɔl',
        'units_sold': 'Yunit dɛn we dɛn dɔn sɛl',
        'stock': 'Stɔk',
        'update': 'Apdet',
        'stock_updated': 'Apdet!',
        'edit_product_details': 'Chenj Prodɔkt Ditels',
        'compare': 'Kɔmpia',
        'remove_from_compare': 'Kɔmɔt am na Kɔmpia',
        'compare_items': 'Kɔmpia di Tin Dɛn',
        'clear_all': 'Klia Ɔl',
        'comparison_limit_error': 'Yu go ebul fɔ kɔmpia nɔmɔ 4 tin.',
        'product_comparison': 'Kɔmpia Prodɔkt Dɛn',
        'remove': 'Kɔmɔt',
        'price': 'Prayz',
        'rating': 'Rɛtin',
        'stock_status': 'Stɔk Stetɔs',
        'in_stock': 'I De',
        'low_stock': 'I de pas',
        'out_of_stock': 'I dɔn dɔn',
        'price_range': 'Prayz Renj',
        'all_prices': 'Ɔl di Prayz dɛn',
        'all_ratings': 'Ɔl di Rɛtin dɛn',
        'four_stars_up': '4 Sta ɛn Ɔp',
        'three_stars_up': '3 Sta ɛn Ɔp',
        'payment_method_description_cod': 'Pe sef sef wit yu krɛdit ɔ dɛbit kad.',
        'payment_method_description_mobile': 'Pe sef sef wit yu dijital wɔlɛt.',
        'mobile_money_number_label': 'Akant Imel / Fon Nɔmba',
        'mobile_money_number_placeholder': 'ɛg, user@example.com',
        'cod_instruction': 'Wi dɔn protɛkt yu pement.',
        'secure_transaction_info': 'Wi dɔn protɛkt yu pement.',
    }
};
